# This is a generated file. Not intended for manual editing.
services:
  auction-svc:
    build:
      context: "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties"
      dockerfile: "src/AuctionService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "rajko1993/auction-svc:dev"
    ports:
    - "127.0.0.1:57038:57100"
    - "127.0.0.1:57238:57300"
    volumes:
    - "C:\\Users\\rajko\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties\\src\\AuctionService:/app:rw"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties:/src:rw"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.2/bin:/riderLogsConf"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_07_21_04_02:/riderLogs:rw"
    working_dir: "/app"
  gateway-svc:
    build:
      context: "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties"
      dockerfile: "src/GatewayService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "rajko1993/gateway-svc:dev"
    ports:
    - "127.0.0.1:57039:57100"
    - "127.0.0.1:57239:57300"
    volumes:
    - "C:\\Users\\rajko\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties\\src\\GatewayService:/app:rw"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties:/src:rw"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.2/bin:/riderLogsConf"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_07_21_04_02:/riderLogs:rw"
    working_dir: "/app"
  identity-svc:
    build:
      context: "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties"
      dockerfile: "src/IdentityService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/IdentityService.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "rajko1993/identity-svc:dev"
    ports:
    - "127.0.0.1:57040:57100"
    - "127.0.0.1:57240:57300"
    volumes:
    - "C:\\Users\\rajko\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties\\src\\IdentityService:/app:rw"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties:/src:rw"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.2/bin:/riderLogsConf"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_07_21_04_02:/riderLogs:rw"
    working_dir: "/app"
  search-svc:
    build:
      context: "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties"
      dockerfile: "src/SearchService/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\rajko\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "rajko1993/search-svc:dev"
    ports:
    - "127.0.0.1:57041:57100"
    - "127.0.0.1:57241:57300"
    volumes:
    - "C:\\Users\\rajko\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties\\src\\SearchService:/app:rw"
    - "C:\\Users\\rajko\\Documents\\UCENJE\\dotNET\\Carsties:/src:rw"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.2/bin:/riderLogsConf"
    - "C:\\Users\\rajko\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_07_21_04_02:/riderLogs:rw"
    working_dir: "/app"
